# Generated by Django 6.0.4 on 2026-04-14 21:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_profiles(apps, schema_editor):
    User = apps.get_model("auth", "User")
    UserProfile = apps.get_model("pharmacy", "UserProfile")
    for u in User.objects.all():
        if not UserProfile.objects.filter(user_id=u.pk).exists():
            UserProfile.objects.create(
                user_id=u.pk,
                role="admin" if u.is_superuser else "worker",
            )


class Migration(migrations.Migration):

    dependencies = [
        ("pharmacy", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="client_recorded_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Device time when sale was recorded (e.g. offline checkout).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="sale",
            name="offline_uuid",
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "role",
                    models.CharField(
                        choices=[("admin", "Administrator"), ("worker", "Worker")],
                        default="worker",
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pharmacy_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.RunPython(seed_profiles, migrations.RunPython.noop),
    ]
