# Generated by Django 6.0.4 on 2026-04-15 14:23

import django.db.models.deletion
from django.db import migrations, models


def backfill_receipts(apps, schema_editor):
    Sale = apps.get_model("pharmacy", "Sale")
    Receipt = apps.get_model("pharmacy", "Receipt")
    for sale in Sale.objects.all().iterator():
        if not Receipt.objects.filter(sale_id=sale.id).exists():
            Receipt.objects.create(
                sale_id=sale.id,
                receipt_number=f"RCPT-{sale.id:08d}",
            )


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0003_stock_movements_audit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(blank=True, max_length=32, unique=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('sale', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='pharmacy.sale')),
            ],
            options={
                'ordering': ['-issued_at', '-id'],
            },
        ),
        migrations.RunPython(backfill_receipts, migrations.RunPython.noop),
    ]
