# Generated by Django 6.0.4 on 2026-04-15 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0004_receipt_storage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('manager', 'Manager / Owner'), ('worker', 'Worker')], default='worker', max_length=20),
        ),
    ]
