# Generated by Django 6.0.4 on 2026-04-15 20:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0005_manager_role_language_tzs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PharmacySubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_on', models.DateField(default=django.utils.timezone.localdate)),
                ('duration_days', models.PositiveIntegerField(default=30)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Pharmacy subscription',
                'verbose_name_plural': 'Pharmacy subscriptions',
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='manager',
            field=models.ForeignKey(blank=True, help_text='Assigned manager for this worker account.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pharmacy_workers', to=settings.AUTH_USER_MODEL),
        ),
    ]
