# Generated by Django 6.0.4 on 2026-04-20 09:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0006_pharmacysubscription_userprofile_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='client_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pharmacy_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='subscription_duration_days',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='subscription_started_on',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
